### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by NataliaLKB**
@msmichellegar @minaorangina 

Both please review :). More tests coming!

### CODE REVIEW

**Comment by msmichellegar** [comment]
I'm getting some errors. Investigating!
screen shot 2015-11-06 at 11 41 39 pm

(sorry added wrong screenshot the first time, see ^^^)

**Comment by iteles** [comment]
Woohoo! If we have time to add [codecov](https://codecov.io/) for coverage, that would be a super interesting thing to show them!

**Comment by NataliaLKB** [comment]
@iteles great shout. @minaorangina have time to add it to the README?

**Comment by iteles** [comment]
@minaorangina Here's the detail on codecov: https://codecov.io/#features

But more interestingly, here's the PR that adds codecov to the https://github.com/dwyl/learn-tdd/ repo (which is useful for an example of implementation so you don't have to go digging :blush:): https://github.com/dwyl/learn-tdd/commit/ff8d8fda32712e2dea2cb15dba49dc38f26f8f4a

**Comment by msmichellegar** [comment]
Are you getting the same error @NataliaLKB?

**Comment by NataliaLKB** [comment]
@msmichellegar no the error you are getting is because your `blog.json` is empty. I will add a function that adds data in for the test.

**Comment by msmichellegar** [comment]
@NataliaLKB Ahh, ok. That makes sense!

**Comment by NataliaLKB** [comment]
@msmichellegar try now!

**Comment by minaorangina** [comment]
@msmichellegar I've reviewed - looks good to me :+1:

**Comment by msmichellegar** [comment]
Perfect!

**Comment by iteles** [comment]
@minaorangina Just checking you also saw the code coverage mentions to you above as they're kind of lost in all the other comments :blush:

**Pull request merged**
