### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by NataliaLKB**
https://github.com/node-girls/workshop/issues/1

@nofootnotes do you agree with these rules?

### CODE REVIEW

**Comment by claireinez** [comment]
Looks good! Would you have time to add in a bit to the readme about this, so people aren't confused? Or will that muddle things?

**Comment by NataliaLKB** [comment]
I will definitely add it to the README as a further reading section in this PR. Really great idea. 

However, since we do have lots of non-beginners coming, I don't think much of an explanation is needed. EditorConfig is widely used and I think most projects/companies lint their code. I will add links to a further resources section.

Who is working on the readme?

**Comment by claireinez** [comment]
Perfect! I actually think we might have overlooked the readme as a task... I won't have time to do it before Saturday - is anyone available?

**Comment by NataliaLKB** [comment]
@nofootnotes please let me know if this change looks good to you, or if you think it requires more of an explanation.

**Comment by claireinez** [comment]
I think that's perfect! If we write more then people might think it's vital for the day, when really we just want to encourage best practices and they can do their own research. Merging now!

**Pull request merged**
